apiVersion: v1
kind: Pod
metadata:
  name: kubia4
spec:
  containers:
    - image: xcorter/kubia4
      name: kubia
      livenessProbe:
        httpGet:
          path: /
          port: 8081
        initialDelaySeconds: 15